#! /bin/sh
### BEGIN INIT INFO
# Provides:             relayr-relayr-system-health-adapter
# Required-Start:       relayr-vertex
# Required-Stop:
# Should-Start:         $local_fs
# Should-Stop:          $local_fs
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    Starts relayr system-health-adapter daemon on port 1833
# Description:          Starts relayr system-health-adapter daemon on port 1833
### END INIT INFO


PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/bin/node
DAEMON_ARGS=/usr/bin/relayr-system-health-adapter
NAME=relayr-system-health-adapter
DESC=relayr-system-health-adapter

PIDFILE=/var/run/relayr-system-health-adapter.pid

test -x $DAEMON || exit 0
test -x $DAEMONBOOTSTRAP || exit 0

set -e

case "$1" in
  start)
        echo -n "Starting $DESC: "
        touch $PIDFILE
        chown root:root $PIDFILE
        if start-stop-daemon --start --background --quiet --pidfile $PIDFILE --chuid root:root --exec $DAEMON -- $DAEMON_ARGS
        then
                echo "$NAME."
        else
                echo "failed"
        fi
        ;;
  stop)
        echo -n "Stopping $DESC: "
        if start-stop-daemon --stop --retry 10 --quiet --oknodo --pidfile $PIDFILE --exec $DAEMON
        then
                echo "$NAME."
        else
                echo "failed"
        fi
        rm -f $PIDFILE
        ;;

  restart|force-reload)
        ${0} stop
        ${0} start
        ;;
  *)
        echo "Usage: /etc/init.d/$NAME {start|stop|restart|force-reload}" >&2
        exit 1
        ;;
esac

exit 0

