name: redis
version: 3.2.3+git
summary: Redis is an in-memory database that persists on disk. http://redis.io
description: |
  Redis is often referred as a data structures server. What this means is
  that Redis provides access to mutable data structures via a set of
  commands, which are sent using a server-client model with TCP sockets and
  a simple protocol. So different processes can query and modify the same
  data structures in a shared way.

  Redis is qithout doubt one of the most popular data stores for scale-out
  cloud architectures.
confinement: devmode

parts:
    redis:
        plugin: make
        source: https://github.com/antirez/redis.git
